package com.example.client.servlet;

import com.google.gwt.user.client.rpc.AsyncCallback;
import com.example.shared.dto.FlashInfoDTO;

import java.util.List;

/**
 * Async interface for FlashInfoService.
 * Generated by GWT for client-side asynchronous RPC calls.
 * Test fixture for GWT RPC analyzer.
 */
public interface FlashInfoServiceAsync {

    /**
     * Create a new flash info message (async).
     *
     * @param dto Flash info data transfer object
     * @param callback Async callback with created flash info
     */
    void createFlashInfo(FlashInfoDTO dto, AsyncCallback<FlashInfoDTO> callback);

    /**
     * Update an existing flash info message (async).
     *
     * @param dto Flash info data transfer object with ID
     * @param callback Async callback with updated flash info
     */
    void updateFlashInfo(FlashInfoDTO dto, AsyncCallback<FlashInfoDTO> callback);

    /**
     * Delete a flash info message by ID (async).
     *
     * @param id Flash info ID
     * @param callback Async callback with deletion result
     */
    void deleteFlashInfo(Long id, AsyncCallback<Boolean> callback);

    /**
     * Get all flash info messages (async).
     *
     * @param callback Async callback with list of flash info messages
     */
    void getAllFlashInfo(AsyncCallback<List<FlashInfoDTO>> callback);

    /**
     * Get flash info by ID (async).
     *
     * @param id Flash info ID
     * @param callback Async callback with flash info or null
     */
    void getFlashInfoById(Long id, AsyncCallback<FlashInfoDTO> callback);

    /**
     * Get active flash info messages (async).
     *
     * @param activeOnly Whether to return only active messages
     * @param callback Async callback with filtered list
     */
    void getFlashInfoFiltered(boolean activeOnly, AsyncCallback<List<FlashInfoDTO>> callback);
}
