apiVersion: v1
kind: ConfigMap
metadata:
  name: chromadb-config
  namespace: chromadb
data:
  ALLOW_RESET: "true"
  ANONYMIZED_TELEMETRY: "false"
  CHROMA_SERVER_HOST: "0.0.0.0"
  CHROMA_SERVER_PORT: "8000"
  CHROMA_SERVER_CORS_ALLOW_ORIGINS: "['*']"
  CHROMA_SERVER_AUTH_CREDENTIALS: ""
  CHROMA_SERVER_AUTH_CREDENTIALS_FILE: ""
  CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER: ""
  CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER_CONFIG: ""
  CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER_CONFIG_FILE: "" 