apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-data
  namespace: chromadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path 