package at.a1ta.cuco.admin.ui.common.client.event;

import at.a1ta.framework.ui.client.event.PortletEventType;

public enum CuCoEventType implements PortletEventType {
  PRODUCT_GROUPUPDATE, LOAD_MESSAGES, ROLE_UPDATE, SELECT_ROLES, UPDATE_USERS, UPDATE_USER, UPDATECREDIT_TYPES, UPDATE_SERVICES, UPDATE_TEAMS, ACTIVATE_TEAM, ADDTEAM_MEMBERS, ADD_SERVICES, REMOVE_SERVICES, UPDATEUNKNOWN_AREACODES, UPDATE_ROLEGROUP, UPDATE_AUTHORITY, UPDATE_TAB, UPDATE_MENU, SEG_SEARCH, SEGSEARCH_EXPORT, SEGIMPORT_MAPPINGUPDATE, SEGIMPORT_MAPPINGHIGHLIGHT;
}
