# Rate Limiting Configuration
# Adjust these settings based on your OpenAI API plan and requirements

# Production settings (conservative)
production:
  requests_per_minute: 30
  requests_per_hour: 1600
  delay_between_requests: 2.0
  exponential_backoff_base: 2.0
  max_retries: 5
  quota_exceeded_wait_time: 3600  # 1 hour wait when quota exceeded
  ollama_timeout: 240  # 4 minutes for Ollama requests (increased for deepseek-r1:70b)

# Test settings (very conservative)
test:
  requests_per_minute: 10
  requests_per_hour: 500
  delay_between_requests: 8.0
  exponential_backoff_base: 2.0
  max_retries: 5
  quota_exceeded_wait_time: 3600  # 1 hour wait when quota exceeded
  ollama_timeout: 180  # 3 minutes for Ollama requests (increased for deepseek-r1:70b)

# Development settings (more aggressive)
development:
  requests_per_minute: 20
  requests_per_hour: 1000
  delay_between_requests: 2.0
  exponential_backoff_base: 2.0
  max_retries: 3
  quota_exceeded_wait_time: 3600  # 1 hour wait when quota exceeded
  ollama_timeout: 180  # 3 minutes for Ollama requests (increased for deepseek-r1:70b)

# Emergency settings (very restrictive)
emergency:
  requests_per_minute: 5
  requests_per_hour: 200
  delay_between_requests: 10.0
  exponential_backoff_base: 2.0
  max_retries: 5
  quota_exceeded_wait_time: 7200  # 2 hours wait when quota exceeded (more conservative)
  ollama_timeout: 120  # 2 minutes for Ollama requests (increased for deepseek-r1:70b) 

# Hardcore 
# Development settings (more aggressive)
hardcore:
  requests_per_minute: 20
  requests_per_hour: 1000
  delay_between_requests: 2.0
  exponential_backoff_base: 2.0
  max_retries: 3
  quota_exceeded_wait_time: 3600  # 1 hour wait when quota exceeded
  ollama_timeout: 180  # 3 minutes for Ollama requests (increased for deepseek-r1:70b)