package at.a1ta.cuco.core.shared.dto.salesinfo;

public enum SalesInfoNoteHistoryModificationType {
  CREATED, CREATED_BY_PREDECESSOR, FOLLOWER_CREATED, MODIFIED, 
  DELETED, ASSIGNED, ORDER_ACCEPTED, IN_PROCESSING, COMPLETED_SUCCESSFULLY, 
  PRODUCT_SAVED, APPOINTMENT_COMMUNICATION
}
