package at.a1ta.cuco.core.shared.dto;

import at.a1ta.bite.core.shared.AuthInfo;

public enum Auth implements AuthInfo {
  // @formatter:off
  CONTENT_MYTODOs("CONTENT_MYTODOs"), SEARCH_CUSTOMERS("FEATURE_SEARCH_CUSTOMERS"),

  FEATURE_SEG_DISPLAY_1("FEATURE_SEG_DISPLAY_1"), FEATURE_SEG_DISPLAY_2("FEATURE_SEG_DISPLAY_2"), FEATURE_SEG_DISPLAY_3("FEATURE_SEG_DISPLAY_3"), FEATURE_SEG_DISPLAY_4("FEATURE_SEG_DISPLAY_4"), FEATURE_SEG_DISPLAY_5(
      "FEATURE_SEG_DISPLAY_5"), CUCO_CREATE_ROLE("FEATURE_ROLLE_ERSTELLEN"), CUCO_CREATE_ROLE_GROUP("FEATURE_ROLLENGRUPPE_ERSTELLEN"), CUCO_EDIT_USER("FEATURE_BENUTZER_AENDERN"), CUCO_DELETE_USER(
      "FEATURE_BENUTZER_LOESCHEN"), CUCO_VIP_STATUS_EDIT("FEATURE_VIP_STATUS_EDIT"),

  PAST_GULA_CREATE("FEATURE_PAST_GULA_CREATE"), PAST_TEAM_CRUD("FEATURE_PAST_TEAM_CRUD"), PAST_TEAM_ASSIGN_SERVICE("FEATURE_PAST_TEAM_ASSIGN_SERVICE"), PAST_TEAM_ASSIGN_USER(
      "FEATURE_PAST_TEAM_ASSIGN_USER"),

  INVOICE_DOWNLOAD("FEATURE_INVOICE_DOWNLOAD"), CONTENT_BILLINGS_OLD_VIEW("CONTENT_BILLINGS_OLD_VIEW"), CONTENT_GUCCI_BILLINGS("CONTENT_GUCCI_BILLINGS"), CONTENT_GUCCI_WIDGETS("CONTENT_GUCCI_WIDGETS"),

  FEATURE_ANB("FEATURE_PRODUCT_ANB"),

  FEATURE_FREEUNITS("FEATURE_FREEUNITS"), FEATURE_MOBILPOINTS("FEATURE_MOBILPOINTS"),

  PRODUCT_BROWSER("CONTENT_PRODUCT_BROWSER"), NEW_PRODUCT_BROWSER("CONTENT_NEW_PRODUCT_BROWSER_TABLE_VIEW"), PRODUCT_BROWSER_IDX_DETAILS("CONTENT_PRODUCT_BROWSER_VIEW_IDX_INFO"), PRODUCT_BROWSER_PRICE_DETAILS(
      "CONTENT_PRODUCT_BROWSER_VIEW_PRICE_INFO"), PRODUCT_BROWSER_A1COACH_DETAILS("CONTENT_PRODUCT_BROWSER_VIEW_A1COACH_INFO"), PRODUCT_BROWSER_MACHBARKEIT_DETAILS(
      "CONTENT_PRODUCT_BROWSER_VIEW_MACHBARKEIT_INFO"), PRODUCT_BROWSER_INSURANCE_DETAILS("CONTENT_PRODUCT_BROWSER_VIEW_INSURANCE_INFO"), PRODUCT_BROWSER_ADDITIONAL_DETAILS(
      "CONTENT_PRODUCT_BROWSER_VIEW_ADDITIONAL_INFO"), PRODUCT_BROWSER_ADDITIONAL_DETAILS_WITH_BUNDLE_PRODUCT("CONTENT_PRODUCT_BROWSER_VIEW_ADDITIONAL_INFO_WITH_BUNDLE_PRODUCT"), PRODUCT_BROWSER_XML_BUTTON_VISIBILITY(
      "CONTENT_PRODUCT_BROWSER_XML_BUTTON_VISIBILITY"),

  USERSHOPASSIGNMENTUPLOADDOWNLOAD("FEATURE_USERSHOPASSIGNMENTUPLOADDOWNLOAD"), QUOTE_CLEARANCE_ADMIN("CONTENT_QUOTE_VALIDATION_ADMINISTRATION"), CREATE_INTERACTION("FEATURE_CREATE_INTERACTION"), CUCO_ADMIN(
      "FEATURE_ADMIN"),

  FEATURE_MYCUCO("FEATURE_MYCUCO"), LINK_SERVICE_ZVERA("LINK_SERVICE_ZVERA"), TARIF_NET_CUBE_XL("TARIF_NET_CUBE_XL"), TARIF_NET_CUBE_M("TARIF_NET_CUBE_M"), TARIF_BREITBAND_PRO_16(
      "TARIF_BREITBAND_PRO_16"), FEATURE_MYCUCO_CUSTOMEREXPORT("FEATURE_MYCUCO_CUSTOMEREXPORT"), LINK_A1COACH("LINK_A1COACH"),

  LINK_ADDRESS("LINK_ADDRESS"), LINK_CORPORATE_DIRECTORY("LINK_CORPORATE_DIRECTORY"), LINK_CSSA("LINK_CSSA"), LINK_ELEARNING("LINK_ELEARNING"), LINK_FRAMEWORK("LINK_FRAMEWORK"), LINK_RDS_INVENTORY(
      "LINK_RDS_INVENTORY"), LINK_SAP("LINK_SAP"), LINK_WEBAC("LINK_WEBAC"), LINK_FEASIBILITY_CHECK("LINK_FEASIBILITY_CHECK"),

  PORTLET_PRINT("FEATURE_PORTLET_PRINT"),

  RESTRICTED_VIEW("FEATURE_CUCO_RESTRICTED_VIEW"), CUSTOMER_UNLOCK_OVERRIDE_ALLOWED("FEATURE_CUSTOMER_UNLOCK_OVERRIDE"),

  TARIFF_GUIDE("FEATURE_TARIFF_GUIDE"), CONTENT_USERTRACKING("CONTENT_USERTRACKING"), CONTENT_USAGEDATA("CONTENT_USAGEDATA"),
  
  RESTRICTED_MOBILE_VIEW("FEATURE_CUCO_RESTRICTED_MOBILE_VIEW"),

  /**
   * Sales Info - Notes
   */
  CONTENT_QUOTE_OVERVIEW("CONTENT_QUOTE_OVERVIEW"), CONTENT_SALES_INFO_ATTRIBUTES("CONTENT_SALES_INFO_ATTRIBUTES"), CONTENT_SALES_INFO_OVERVIEW("CONTENT_SALES_INFO_OVERVIEW"), CONTENT_SALES_INFO_COMPACT_OVERVIEW(
      "CONTENT_SALES_INFO_COMPACT_OVERVIEW"), VIEW_QUOTE("VIEW_QUOTE"),

  SI_SIMPLE_NOTE_VIEW("FEATURE_SI_SIMPLE_NOTE_VIEW"), SI_SIMPLE_NOTE_EDIT("FEATURE_SI_SIMPLE_NOTE_EDIT"), SI_SIMPLE_NOTE_DELETE("FEATURE_SI_SIMPLE_NOTE_DELETE"),

  SI_COMPETITOR_NOTE_VIEW("FEATURE_SI_COMPETITOR_NOTE_VIEW"), SI_COMPETITOR_NOTE_EDIT("FEATURE_SI_COMPETITOR_NOTE_EDIT"), SI_COMPETITOR_NOTE_DELETE("FEATURE_SI_COMPETITOR_NOTE_DELETE"),

  SI_VR_SBS_NOTE_VIEW("FEATURE_SI_VR_SBS_NOTE_VIEW"), SI_VR_SBS_NOTE_EDIT("FEATURE_SI_VR_SBS_NOTE_EDIT"), SI_VR_SBS_NOTE_DELETE("FEATURE_SI_VR_SBS_NOTE_DELETE"), SI_VR_SBS_NOTE_ADMIN(
      "FEATURE_SI_VR_SBS_NOTE_ADMIN"), SI_VR_SBS_NOTE_REPORT("FEATURE_SI_VR_SBS_NOTE_REPORT"), FEATURE_SI_VR_SBS_NOTE_TODO_EDIT("FEATURE_SI_VR_SBS_NOTE_TODO_EDIT"),

  SI_VR_DS_NOTE_VIEW("FEATURE_SI_VR_DS_VIEW"), SI_VR_DS_NOTE_EDIT("FEATURE_SI_VR_DS_EDIT"), SI_VR_DS_NOTE_DELETE("FEATURE_SI_VR_DS_DELETE"), FEATURE_SI_VR_DS_NOTE_ADMIN("FEATURE_SI_VR_DS_NOTE_ADMIN"),
  
  SI_VR_SBS_PRODUCT_NOTE_VIEW_IN_OVERVIEW("FEATURE_SI_VR_SBS_PRODUCT_NOTE_VIEW_IN_OVERVIEW"), SI_VR_SBS_PRODUCT_NOTE_EDIT_IN_OVERVIEW("FEATURE_SI_VR_SBS_PRODUCT_NOTE_EDIT_IN_OVERVIEW"), SI_VR_SBS_PRODUCT_NOTE_DELETE_IN_OVERVIEW(
      "FEATURE_SI_VR_SBS_PRODUCT_NOTE_DELETE_IN_OVERVIEW"),

  SI_VR_GENERIC_NOTE_VIEW("FEATURE_SI_VR_GENERIC_NOTE_VIEW"), SI_VR_GENERIC_NOTE_EDIT("FEATURE_SI_VR_GENERIC_NOTE_EDIT"), SI_VR_GENERIC_NOTE_DELETE("FEATURE_SI_VR_GENERIC_NOTE_DELETE"), SI_VR_GENERIC_NOTE_ADMIN(
      "FEATURE_SI_VR_GENERIC_NOTE_ADMIN"), SI_VR_GENERIC_NOTE_REPORT("FEATURE_SI_VR_GENERIC_NOTE_REPORT"),

  SI_VR_ANGEBOTE_VIEW("FEATURE_SI_VR_ANGEBOTE_VIEW"), SI_VR_ANGEBOTE_EDIT("FEATURE_SI_VR_ANGEBOTE_EDIT"), SI_VR_ANGEBOTE_DELETE("FEATURE_SI_VR_ANGEBOTE_DELETE"),

  SI_SALES_CONV_NOTE_VIEW("FEATURE_SI_SALES_CONV_NOTE_VIEW"), SI_SALES_CONV_NOTE_EDIT("FEATURE_SI_SALES_CONV_NOTE_EDIT"), SI_SALES_CONV_NOTE_DELETE("FEATURE_SI_SALES_CONV_NOTE_DELETE"),

  SI_SALES_CONV_PRODUCT_NOTE_VIEW_IN_OVERVIEW("FEATURE_SI_SALES_CONV_PRODUCT_NOTE_VIEW_IN_OVERVIEW"), SI_SALES_CONV_PRODUCT_NOTE_EDIT_IN_OVERVIEW("FEATURE_SI_SALES_CONV_PRODUCT_NOTE_EDIT_IN_OVERVIEW"), SI_SALES_CONV_PRODUCT_NOTE_DELETE_IN_OVERVIEW(
      "FEATURE_SI_SALES_CONV_PRODUCT_NOTE_DELETE_IN_OVERVIEW"),
  
  NC_VIEW("NC_VIEW"), NC_EDIT("NC_EDIT"), NC_MERGE("NC_MERGE"), SEND_POS_ASSIGNMENT_EMAIL("FEATURE_SEND_POS_ASSIGNMENT_EMAIL"), PASSWORD("FEATURE_PASSWORD"), CONTENT_BUELINKS("CONTENT_BUELINKS"), CONTENT_LINKS("CONTENT_LINKS"), BSNOTES_MENU_ENTRY(
      "BSNOTES_MENU_ENTRY"),

	A1BIP_SHOW_BUSINESS_FIREWALL("FEATURE_A1BIP_SHOW_BUSINESS_FIREWALL"),
	
  A1BI_SHOW_BUSINESS_FIREWALL("FEATURE_A1BI_SHOW_BUSINESS_FIREWALL"),
  
  A1BI_SHOW_MARKETPLACE("FEATURE_A1BI_SHOW_MARKETPLACE"),
  
  A1BN_SHOW_MARKETPLACE("FEATURE_A1BN_SHOW_MARKETPLACE"),
  
  ETGT_SHOW_MARKETPLACE("FEATURE_A1ETGT_SHOW_MARKETPLACE"),

  CM_BUDDY_LINK("FEATURE_CM_BUDDY_LINK"), PKB_GUCCI_BUDDY("PKB_GUCCI_BUDDY"),
	
  CONTENT_PRODUCTLINK_ONECOCKPIT("CONTENT_PRODUCTLINK_ONECOCKPIT"),

  FEATURE_ANZEIGE_KREDITLIMIT("FEATURE_ANZEIGE_KREDITLIMIT"),

  CCS_SHOW_MARKETPLACE("FEATURE_A1CCS_SHOW_MARKETPLACE"),

  DAAS_SHOW_SPECIAL_PRICE_GROUP("FEATURE_DAAS_SHOW_Special_Pricegroup");

  // @formatter:on

  private final String name;

  private Auth(String name) {
    this.name = name;
  }

  @Override
  public String getName() {
    return name;
  }
}