<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <groupId>com.test</groupId>
    <artifactId>test-project</artifactId>
    <version>1.0.0</version>

    <dependencies>
        <dependency>
            <groupId>at.a1ta.cuco</groupId>
            <artifactId>cuco-cct-core</artifactId>
        </dependency>
    </dependencies>
</project>
