# Application Configuration

# Model Settings
embedding_model: "all-MiniLM-L6-v2"
clustering:
  algorithm: "kmeans"
  n_clusters: 10
  random_state: 42

# ChromaDB Settings
chroma:
  collection_name: "code_artifacts"
  persist_directory: "data/chroma_db"

# OpenAI Settings
openai:
  model: "gpt-4-turbo-preview"
  temperature: 0.7
  max_tokens: 500

# Processing Settings
processing:
  batch_size: 32
  max_artifacts_per_file: 1000 